apiVersion: v1
kind: Service
metadata:
  name: my-internal-service 
spec:
  ports:
  - name: my-service-name-1
    port: 81
    targetPort: 8081
  selector:
    app: my-statefulset-pod-label
  type: ClusterIP
