apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mydisk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-persistent-volume-2
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: mydisk2
    fsType: ext4
